services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data

  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  django:
    build:
      context: backend
    entrypoint: /app/entrypoint.sh
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  bot:
    build:
      context: backend
    command: python /app/main.py
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery:
    build:
      context: backend
    restart: always
    command: celery -A backend worker -l info --logfile /app/logs/celery.log
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - django

  celery-beat:
    build:
      context: backend
    restart: always
    command: celery -A backend beat -l info --logfile /app/logs/celery.log
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - django

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static:/var/www/static
    depends_on:
      - celery
      - celery-beat
