# Generated by Django 5.2 on 2025-04-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='astropoints',
            field=models.IntegerField(default=0, verbose_name='Астробаллы'),
        ),
        migrations.AddField(
            model_name='client',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_friends', to=settings.AUTH_USER_MODEL, verbose_name='Кем приглашен'),
        ),
    ]
