# Generated by Django 5.2 on 2025-04-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_astropoints_client_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_friends', to='core.client', verbose_name='Кем приглашен'),
        ),
    ]
