# Generated by Django 5.2 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип подписки'),
        ),
    ]
