# Generated by Django 5.2 on 2025-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
