# Generated by Django 5.2 on 2025-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailyquest_weeklyquest_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyquest',
            options={'verbose_name': 'Еженедельный квест', 'verbose_name_plural': 'Еженедельные квесты'},
        ),
        migrations.AddField(
            model_name='weeklyquesttask',
            name='text',
            field=models.TextField(default='сложное задание', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
