# Generated by Django 5.2 on 2025-04-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_weeklyquest_options_weeklyquesttask_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientdailyquest',
            unique_together=set(),
        ),
    ]
