# Generated by Django 5.2 on 2025-04-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clientdailyquest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='client',
            name='notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Уведомления'),
        ),
        migrations.CreateModel(
            name='ClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('your_compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('friday_gift', 'Пятничный подарок')], max_length=100, verbose_name='Действие')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.client')),
            ],
            options={
                'verbose_name': 'Действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-date'],
            },
        ),
    ]
