# Generated by Django 5.2 on 2025-04-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_client_fullname_client_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientweeklyquesttask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quests_tasks', to='core.client', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ClientWeeklyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quests', to='core.client', verbose_name='Пользователь')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.weeklyquest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Запись на еженедельный квест',
                'verbose_name_plural': 'Записи на еженедельные квесты',
                'ordering': ['-date'],
                'unique_together': {('client', 'quest')},
            },
        ),
    ]
