# Generated by Django 5.2 on 2025-04-24 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_clientweeklyquesttask_client_clientweeklyquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='Авторитет'),
        ),
        migrations.AddField(
            model_name='client',
            name='centers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None, verbose_name='Центры'),
        ),
        migrations.AddField(
            model_name='client',
            name='gates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None, verbose_name='Ворота'),
        ),
        migrations.AddField(
            model_name='client',
            name='planets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None, verbose_name='Планеты'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.CharField(blank=True, max_length=255, verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='client',
            name='strategy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стратегия'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='client',
            name='tzone',
            field=models.FloatField(null=True, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('standard', '✨ SoulMind Стандарт'), ('premium', '💎 SoulMind Премиум')], max_length=50, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='action',
            field=models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='clientdailyquest',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', '⚡ Выполнил(а)!'), ('skipped', '⏭ Пропустить')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='clientweeklyquesttask',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', '⚡ Выполнил(а)!'), ('skipped', '⏭ Пропустить')], max_length=50, verbose_name='Статус'),
        ),
    ]
