# Generated by Django 5.2 on 2025-04-24 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_authority_client_centers_client_gates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='centers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Центры'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Ворота'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None, verbose_name='Планеты'),
        ),
    ]
