# Generated by Django 5.2 on 2025-04-25 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='channels_long',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None, verbose_name='Каналы'),
        ),
        migrations.AddField(
            model_name='client',
            name='definition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Определение'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='houses',
        ),
        migrations.AddField(
            model_name='client',
            name='houses',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Дома'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='planets',
        ),
        migrations.AddField(
            model_name='client',
            name='planets',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Планеты'),
        ),
    ]
