# Generated by Django 5.2 on 2025-04-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_questtag_remove_dailyquest_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActionBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_actions', to='core.client')),
            ],
            options={
                'verbose_name': 'Покупка пользователя',
                'verbose_name_plural': 'Покупки пользователей',
                'ordering': ['-date'],
            },
        ),
    ]
