# Generated by Django 5.2 on 2025-04-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientactionbuying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Метка')),
            ],
        ),
        migrations.AlterModelOptions(
            name='monthtext',
            options={'ordering': ['-created_at'], 'verbose_name': 'Текст из "Месяц с Soul Muse"', 'verbose_name_plural': 'Тексты из "Месяц с Soul Muse"'},
        ),
        migrations.AlterField(
            model_name='monthtext',
            name='type',
            field=models.CharField(choices=[('month_forecast', 'Персональный прогноз на месяц'), ('month_main_resource', 'Главный ресурс месяца'), ('month_script', 'Твой сценарий месяца')], max_length=100, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='MiniConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('audio_file_id', models.TextField(blank=True, null=True, verbose_name='ID аудиофайла в телеграм')),
                ('expert_type', models.CharField(choices=[('astrologist', 'Астролог'), ('numerologist', 'Нумеролог'), ('psychologist', 'Психолог'), ('hd_analyst', 'Аналитик Human Design'), ('spiritual_mentor', 'Духовный наставник-энергопрактик')], max_length=50, verbose_name='Тип эксперта')),
                ('intention', models.CharField(choices=[('find_inner_answers', 'Найти внутренние ответы'), ('solve_certain_problem', 'Решить конкретную проблему'), ('curiosity', 'Любопытство')], max_length=50, verbose_name='Намерение')),
                ('experience_type', models.CharField(choices=[('first_time', 'Впервые'), ('some_experience', 'У меня есть небольшой опыт'), ('pro', 'Я практик или профи')], max_length=50, verbose_name='Уже сталкивался')),
                ('feelings_type', models.CharField(choices=[('in_resource', 'В ресурсе'), ('in_search', 'В поиске'), ('at_bottom', 'У дна (но чувствую движение)')], max_length=50, verbose_name='Как себя чувствует')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_consults', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мини-консультация',
                'verbose_name_plural': 'Мини-консультации',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_id', models.TextField(verbose_name='ID аудиофайла в телеграм')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.client', verbose_name='Эксперт')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.miniconsult')),
            ],
            options={
                'verbose_name': 'Ответ эксперта',
                'verbose_name_plural': 'Ответы экспертов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MiniConsultFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('good', 'В точку'), ('not_bad', 'Неплохо, но можно глубже'), ('bad', 'Не отозвалось')], max_length=50, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('audio_file_id', models.TextField(blank=True, null=True, verbose_name='ID аудиофайла в телеграм')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.miniconsult')),
            ],
            options={
                'verbose_name': 'Фидбек после мини-консультации',
                'verbose_name_plural': 'Фидбек после мини-консультаций',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MiniConsultTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.miniconsult')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consults', to='core.topic')),
            ],
        ),
    ]
