# Generated by Django 5.2 on 2025-04-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_topic_alter_monthtext_options_alter_monthtext_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulMuseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вопрос к Soul Muse',
                'verbose_name_plural': 'Вопросы к Soul Muse',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AddField(
            model_name='topic',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Виден всем'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='action',
            field=models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('universe_advice', 'Совет вселенной'), ('personal_day', 'Твой личный день'), ('destiny_guide', 'Путеводитель судьбы'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='clientactionbuying',
            name='action',
            field=models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('universe_advice', 'Совет вселенной'), ('personal_day', 'Твой личный день'), ('destiny_guide', 'Путеводитель судьбы'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Метка'),
        ),
        migrations.CreateModel(
            name='FridayGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('insight_phrases', 'Инсайт'), ('cards', 'Карта Soul Muse'), ('symbols', 'Интуитивный символ / образ недели')], max_length=50, verbose_name='Тип подарка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('audio_file_id', models.TextField(blank=True, null=True, verbose_name='ID аудиофайла в телеграм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_gifts', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пятничный подарок',
                'verbose_name_plural': 'Пятничные подарки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('audio_file_id', models.TextField(blank=True, null=True, verbose_name='ID аудиофайла в телеграм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инсайт',
                'verbose_name_plural': 'Инсайты',
                'ordering': ['-created_at'],
            },
        ),
    ]
