# Generated by Django 5.2 on 2025-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_soulmusequestion_alter_topic_options_topic_is_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulmusequestion',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
    ]
