# Generated by Django 5.2 on 2025-04-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_client_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='aspects',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Аспекты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_friends', to='core.client', verbose_name='Кем приглашен'),
        ),
        migrations.CreateModel(
            name='ClientQuestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.client')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.questtag')),
            ],
        ),
    ]
