# Generated by Django 5.2 on 2025-04-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_client_aspects_alter_client_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientquesttag',
            options={'verbose_name': 'Тег пользователя', 'verbose_name_plural': 'Теги пользователей'},
        ),
        migrations.AlterModelOptions(
            name='dailyquesttag',
            options={'verbose_name': 'Тег ежедневного квеста', 'verbose_name_plural': 'Теги ежедневных квестов'},
        ),
        migrations.AlterModelOptions(
            name='weeklyquesttag',
            options={'verbose_name': 'Тег еженедельного квеста', 'verbose_name_plural': 'Теги еженедельных квестов'},
        ),
        migrations.RemoveField(
            model_name='dailyquest',
            name='description',
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='text',
            field=models.TextField(default='quest', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyquesttask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='weeklyquesttask',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Видна всем'),
        ),
        migrations.AlterField(
            model_name='weeklyquest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='weeklyquesttask',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
