# Generated by Django 5.2.1 on 2025-05-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_clientquesttag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdailyquest',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', '⚡ {gender:Выполнил,Выполнила}!'), ('skipped', '⏭ Пропустить')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='clientweeklyquesttask',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', '⚡ {gender:Выполнил,Выполнила}!'), ('skipped', '⏭ Пропустить')], max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ClientActionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('universe_advice', 'Совет вселенной'), ('personal_day', 'Твой личный день'), ('destiny_guide', 'Путеводитель судьбы'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие')),
                ('subscription_plan', models.CharField(blank=True, choices=[('standard', '✨ SoulMind Стандарт'), ('premium', '💎 SoulMind Премиум')], max_length=50, verbose_name='Тип подписки')),
                ('free_limit', models.PositiveIntegerField(verbose_name='Осталось')),
                ('extra_limit', models.PositiveIntegerField(default=0, verbose_name='Докуплено')),
                ('updated_at', models.DateTimeField(verbose_name='Последнее обновление лимитов')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='core.client')),
            ],
            options={
                'verbose_name': 'Лимит пользователя',
                'verbose_name_plural': 'Лимиты пользователей',
                'ordering': ['-updated_at'],
                'unique_together': {('client', 'action')},
            },
        ),
        migrations.DeleteModel(
            name='ClientActionBuying',
        ),
    ]
