# Generated by Django 5.2.1 on 2025-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_clientdailyquest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniconsult',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='miniconsult',
            name='intention',
            field=models.CharField(max_length=255, verbose_name='Намерение'),
        ),
    ]
