# Generated by Django 5.2.1 on 2025-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_miniconsult_completed_alter_miniconsult_intention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniconsult',
            name='completed',
        ),
        migrations.AddField(
            model_name='client',
            name='expert_type',
            field=models.CharField(blank=True, choices=[('astrologist', 'Астролог'), ('numerologist', 'Нумеролог'), ('psychologist', 'Психолог'), ('hd_analyst', 'Аналитик Human Design'), ('spiritual_mentor', 'Духовный наставник-энергопрактик')], max_length=50, verbose_name='Тип эксперта'),
        ),
        migrations.AddField(
            model_name='miniconsult',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('in_progress', 'В обработке'), ('completed', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
