# Generated by Django 5.2.1 on 2025-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_monthtext_script_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertanswer',
            name='audio_file_path',
            field=models.CharField(default='voice/file_1.ogg', max_length=255, verbose_name='Путь к файлу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miniconsult',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к файлу'),
        ),
        migrations.AddField(
            model_name='miniconsultfeedback',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к файлу'),
        ),
    ]
