# Generated by Django 5.2.1 on 2025-05-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_expertanswer_audio_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('astrologist', 'Астролог'), ('numerologist', 'Нумеролог'), ('psychologist', 'Психолог'), ('hd_analyst', 'Аналитик Human Design'), ('spiritual_mentor', 'Духовный наставник-энергопрактик')], max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип эксперта',
                'verbose_name_plural': 'Типы экспертов',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='expert_type',
        ),
        migrations.CreateModel(
            name='ClientExpertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_types', to='core.client', verbose_name='Пользователь')),
                ('expert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.experttype', verbose_name='Тип эксперта')),
            ],
        ),
        migrations.RemoveField(
            model_name='miniconsult',
            name='expert_type',
        ),
        migrations.AddField(
            model_name='miniconsult',
            name='expert_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_consults', to='core.experttype', verbose_name='Тип эксперта'),
        ),
    ]
