# Generated by Django 5.2.3 on 2025-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_client_email_alter_client_birth_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientexperttype',
            options={'verbose_name': 'Тип эксперта', 'verbose_name_plural': 'Типы экспертов'},
        ),
        migrations.AddField(
            model_name='miniconsult',
            name='photo_file_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID аудиофайла в телеграм'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='action',
            field=models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('weekly_quest', 'Участие в еженедельном квесте'), ('universe_advice', 'Совет вселенной'), ('personal_day', 'Твой личный день'), ('destiny_guide', 'Путеводитель судьбы'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='clientactionlimit',
            name='action',
            field=models.CharField(choices=[('compatability_energy', 'Энергия вашей совместимости'), ('soul_muse_question', 'Спроси у Soul Muse'), ('weekly_quest', 'Участие в еженедельном квесте'), ('universe_advice', 'Совет вселенной'), ('personal_day', 'Твой личный день'), ('destiny_guide', 'Путеводитель судьбы'), ('friday_gift', 'Пятничный подарок'), ('power_day', 'Твой День силы'), ('universe_answer', 'Ответ Вселенной'), ('soul_muse_vip_answer', 'VIP-совет от Soul Muse')], max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='experttype',
            name='name',
            field=models.CharField(choices=[('astrologist', 'Астролог'), ('numerologist', 'Нумеролог'), ('psychologist', 'Психолог'), ('hd_analyst', 'Эксперт Human Design'), ('spiritual_mentor', 'Духовный наставник-энергопрактик')], max_length=255, unique=True),
        ),
    ]
