# Generated by Django 5.2.3 on 2025-07-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_clientexperttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTag',
            fields=[
                ('tag', models.CharField(help_text='Только английские буквы, цифры и нижние подчеркивания', max_length=25, primary_key=True, serialize=False, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'UTM-Метка',
                'verbose_name_plural': 'UTM-Метка',
            },
        ),
        migrations.AlterModelOptions(
            name='expertanswer',
            options={'ordering': ['date'], 'verbose_name': 'Ответ эксперта', 'verbose_name_plural': 'Ответы экспертов'},
        ),
        migrations.AddField(
            model_name='miniconsult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('trial', 'Тестовый период'), ('standard', '✨ SoulMind Стандарт'), ('premium', '💎 SoulMind Премиум')], max_length=50, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='clientactionlimit',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('trial', 'Тестовый период'), ('standard', '✨ SoulMind Стандарт'), ('premium', '💎 SoulMind Премиум')], max_length=50, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='miniconsult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_subscription', models.CharField(blank=True, choices=[('trial', 'Тестовый период'), ('standard', '✨ SoulMind Стандарт'), ('premium', '💎 SoulMind Премиум')], max_length=50, verbose_name='Тип подписки на момент покупки')),
                ('purchase_type', models.CharField(choices=[('standard_subscription', 'Standard Subscription'), ('premium_subscription', 'Premium Subscription'), ('mini_consult', 'Mini Consult'), ('vip_personal_report', 'Vip Personal Report'), ('vip_compatability', 'Vip Compatability'), ('extra_compatability', 'Extra Compatability'), ('extra_soul_muse_question', 'Extra Soul Muse Question')], max_length=100, verbose_name='Тип оплаты')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатная покупка')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Значение')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='source_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.sourcetag', verbose_name='UTM Метка'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
